name: Create a (Pre)release on NuGet

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
    - "v[0-9]+.[0-9]+.[0-9]+-preview[0-9]+"

jobs:
  release-nuget:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Verify commit exists in origin/master
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/master
      - name: Get version information from tag
        id: get_version
        run: |
          version="${GITHUB_REF_NAME#v}"
          echo "version-without-v=$version" >> $GITHUB_OUTPUT
      - name: Pack
        run: dotnet pack src/Ecia.Barcode.Parser/Ecia.Barcode.Parser.csproj -c Release -p:PackageVersion=${{ steps.get_version.outputs.version-without-v }}
      - name: Push
        run: dotnet nuget push src/Ecia.Barcode.Parser/bin/Release/Ecia.Barcode.Parser.${{ steps.get_version.outputs.version-without-v }}.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.NUGET_API_KEY }}
